#!/usr/bin/env python3

import sys
from subprocess import call

if sys.argv[1] == 'status':
    call('sudo iptables-save'.split())
    call('sudo sysctl net.ipv4.ip_forward'.split())
if sys.argv[1] == 'on':
    call(['sudo','iptables','-t','nat','-A','POSTROUTING','-o',sys.argv[2],'-j','MASQUERADE'])
    call('sudo sysctl net.ipv4.ip_forward=1'.split())
if sys.argv[1] == 'off':
    call("sudo iptables-save | grep MASQUERADE | sed 's/-A/-D/' | while read i ; do sudo iptables -t nat $i ; done",shell=True)
    call('sudo sysctl net.ipv4.ip_forward=0'.split())
